const SURFACES = [
  {
    key: 'facebook_cover',
    displayName: 'Facebook Cover',
    category: 'social',
    targetWidth: 1640,
    targetHeight: 924,
    aspect: '16:9',
    geminiAspect: '16:9',
    postResizeNeeded: true,
    logoZone: 'left',
    seedPrompt: "A close-crop photograph of a woman's hands working with cream silk fabric on a pale wooden table. Mid-action — one hand smoothing the fabric, fingers slightly lifted, a few stainless steel sewing pins resting nearby. Natural window light from the upper left, late morning, no flash. The silk has a subtle sheen and visible weave texture. A small piece of natural linen sits at the edge of the frame. Shot from a slight overhead angle, medium-format film aesthetic, gentle grain, very soft contrast. Palette: ivory, oyster, wheat, raw wood tones, dove gray. The hands and fabric sit in the right two-thirds of the frame; the left third is the wooden table surface, uncluttered, empty negative space for text. No faces visible, hands only. No text, no logos, no jewelry. Editorial fashion still-life style, quiet and unposed. Aspect ratio 16:9.",
    notes: 'Mobile crop center is 820×312 — logo composite must sit in the centred safe zone',
  },
  {
    key: 'facebook_profile',
    displayName: 'Facebook Profile Photo',
    category: 'social',
    targetWidth: 320,
    targetHeight: 320,
    aspect: '1:1',
    geminiAspect: '1:1',
    postResizeNeeded: true,
    logoZone: 'center',
    seedPrompt: 'A square close-up photograph of folded cream silk fabric in soft natural light, very gentle texture and subtle fold lines. Palette: ivory, oyster, the faintest wheat. Calm uniform composition with slightly more interesting texture in the center where a monogram will overlay. No people, no text, no logos. Editorial fashion still-life, restrained. Aspect ratio 1:1.',
    notes: 'Displayed as circle on Facebook — composition must work cropped to circle',
  },
  {
    key: 'instagram_profile',
    displayName: 'Instagram Profile Photo',
    category: 'social',
    targetWidth: 320,
    targetHeight: 320,
    aspect: '1:1',
    geminiAspect: '1:1',
    postResizeNeeded: true,
    logoZone: 'center',
    seedPrompt: 'A square close-up photograph of folded cream silk fabric in soft natural light, very gentle texture and subtle fold lines. Palette: ivory, oyster, the faintest wheat. Calm uniform composition with slightly more interesting texture in the center where a monogram will overlay. No people, no text, no logos. Editorial fashion still-life, restrained. Aspect ratio 1:1.',
    notes: 'Displayed as circle on Instagram — composition must work cropped to circle',
  },
  {
    key: 'instagram_story_bg',
    displayName: 'Instagram Story Background',
    category: 'social',
    targetWidth: 1080,
    targetHeight: 1920,
    aspect: '9:16',
    geminiAspect: '9:16',
    postResizeNeeded: false,
    logoZone: 'center',
    seedPrompt: 'A vertical close-up photograph of cream silk fabric draped softly, with visible weave texture and natural folds. Soft afternoon light from one side, no flash, very gentle highlights along the fabric ridges. The fabric fills the whole frame but with rhythm — folds creating natural lines that lead the eye toward the center. Palette: ivory, cream, oyster, the lightest wheat. Medium-format film aesthetic with subtle grain. Top third and bottom third of the frame are slightly more uniform fabric for text overlay; middle third has the most interesting fold detail. No people, no text, no logos, no embellishment. Editorial fashion close-up, quiet, restrained. Aspect ratio 9:16.',
    notes: 'Top and bottom thirds are safe text zones for Story stickers and CTAs',
  },
  {
    key: 'instagram_post',
    displayName: 'Instagram Feed Post (4:5)',
    category: 'social',
    targetWidth: 1080,
    targetHeight: 1350,
    aspect: '4:5',
    geminiAspect: '4:5',
    postResizeNeeded: false,
    logoZone: 'none',
    seedPrompt: 'A vertical editorial photograph of cream silk and oyster linen layered together, soft natural morning light from a window. Visible weave structure on both fabrics, gentle folds, no shadows. Palette: ivory, oyster, wheat, dove gray. Medium-format film aesthetic, very subtle grain, soft contrast. Composition has visual interest throughout the frame with rhythm but no busy areas. No people, no text, no logos. Editorial fashion close-up, restrained and quiet. Aspect ratio 4:5.',
    notes: 'Standard feed post ratio — no logo composite needed, the post is the imagery alone',
  },
  {
    key: 'pinterest_pin',
    displayName: 'Pinterest Pin',
    category: 'social',
    targetWidth: 1000,
    targetHeight: 1500,
    aspect: '2:3',
    geminiAspect: '2:3',
    postResizeNeeded: false,
    logoZone: 'top',
    seedPrompt: 'A vertical photograph of silk and linen pieces hanging from a wooden dowel against a pale plaster wall. Soft natural light from the left, midday. Three or four pieces visible — silk slip, linen camisole, silk wrap — in shades of ivory, oyster, and wheat. The wall behind is uneven plaster with subtle texture, slightly warmer in tone than the fabric. Shot from below at a slight angle so the pieces hang naturally with gentle drape. Palette: ivory, oyster, wheat, plaster cream, raw wood. Medium-format film aesthetic, subtle grain, very soft contrast. The top quarter of the frame is just the wall — empty space for a title overlay. No people, no text, no logos. Editorial fashion lookbook style, restrained and quiet. Aspect ratio 2:3.',
    notes: 'Title overlay goes in the top quarter after compositing',
  },
  {
    key: 'pinterest_profile',
    displayName: 'Pinterest Profile Photo',
    category: 'social',
    targetWidth: 165,
    targetHeight: 165,
    aspect: '1:1',
    geminiAspect: '1:1',
    postResizeNeeded: true,
    logoZone: 'center',
    seedPrompt: 'A square close-up photograph of folded cream silk fabric in soft natural light, very gentle texture and subtle fold lines. Palette: ivory, oyster, the faintest wheat. Calm uniform composition with slightly more interesting texture in the center where a monogram will overlay. No people, no text, no logos. Editorial fashion still-life, restrained. Aspect ratio 1:1.',
    notes: 'Displayed as circle — composition must work cropped to circle',
  },
  {
    key: 'email_header',
    displayName: 'Email Header (Resend)',
    category: 'email',
    targetWidth: 1200,
    targetHeight: 400,
    aspect: '3:1',
    geminiAspect: '16:9',
    postResizeNeeded: true,
    logoZone: 'center',
    seedPrompt: 'A wide horizontal photograph of folded silk and linen seen from directly above, abstract and close. The fabric fills the entire frame in soft, overlapping folds. Cream silk and oyster linen layered together, gentle creases catching the soft window light from one side. Palette: ivory, cream, oyster, the faintest wheat. Very soft contrast, almost no shadows, gentle film grain. No people, no text, no logos, no embellishment. Aspect ratio 3:1, panoramic. Editorial fashion close-up texture study.',
    notes: 'Crop top and bottom from a 16:9 generation to get true 3:1',
  },
  {
    key: 'etsy_banner',
    displayName: 'Etsy Shop Banner',
    category: 'marketplace',
    targetWidth: 1200,
    targetHeight: 300,
    aspect: '4:1',
    geminiAspect: '16:9',
    postResizeNeeded: true,
    logoZone: 'center',
    seedPrompt: 'A wide panoramic photograph of folded cream silk and oyster linen seen from directly above. The fabric is arranged in three distinct folds across the frame, with subtle texture variation between them. Soft window light from the upper edge, no shadows. Palette: ivory, oyster, wheat, the faintest cream. Medium-format film aesthetic, very subtle grain. The center of the frame has slightly calmer, more uniform fabric for a logo overlay; the left and right thirds have the most interesting fold detail. No people, no text, no logos. Editorial fashion still-life. Aspect ratio 4:1, very wide.',
    notes: 'Heavy crop top and bottom — very wide 4:1 panoramic',
  },
  {
    key: 'journal_article_header',
    displayName: 'Journal Article Header',
    category: 'social',
    targetWidth: 1600,
    targetHeight: 900,
    aspect: '16:9',
    geminiAspect: '16:9',
    postResizeNeeded: true,
    logoZone: 'none',
    seedPrompt: 'A wide photograph of a sewing machine on a wooden table, half in shadow, half catching soft window light. A length of cream silk is partially threaded through the machine, draping gently to the side. A pair of scissors and a few pins rest nearby. Late morning light from a window on the left, very soft and diffuse. Palette: ivory, oyster, raw wood, the faintest warm gray, deep shadow tones. Medium-format film aesthetic, gentle grain, soft contrast. No people visible, no text, no logos. Editorial fashion documentary style — like a glimpse into a quiet working studio. Aspect ratio 16:9.',
    notes: 'Used as cover image on individual Journal articles. No logo overlay — article title is rendered by the site.',
  },
];

module.exports = SURFACES;
