/**
 * SILKILINEN nightly backup → Cloudflare R2.
 *
 * Why this script exists: MongoDB Atlas free tier has NO automated backups.
 * If the cluster ever resets or is compromised, EVERYTHING (orders,
 * customers, reviews, journal articles, AI sessions, promo codes) is gone.
 * This dumps every collection, gzips the result, and uploads to R2 with the
 * date in the key. Pairs with backend/scripts/restoreFromBackup.js.
 *
 * Pure-Node dump (no mongodump system dependency). The format is a single
 * gzipped JSON object:  { meta: {...}, collections: { name: [docs, ...] } }
 * — restorable by restoreFromBackup.js or any tool that can read JSON.
 *
 * Schedule: run nightly as a Railway Cron Service (the API service stays
 * untouched). See SETUP at the bottom of this comment.
 *
 * Required env vars (set on the cron service):
 *   MONGODB_URI            — same connection string the API uses
 *   R2_ACCOUNT_ID          — Cloudflare account id
 *   R2_ACCESS_KEY_ID       — R2 access key id
 *   R2_SECRET_ACCESS_KEY   — R2 secret access key
 *   R2_BUCKET              — bucket name, e.g. "silkilinen-backups"
 *
 * Optional env vars:
 *   BACKUP_RETENTION_DAYS  — delete archives older than N days (default 30)
 *   BACKUP_NOTIFY_EMAIL    — failure alerts (uses Resend if RESEND_API_KEY set)
 *   ADMIN_EMAIL            — fallback for BACKUP_NOTIFY_EMAIL
 *
 * SETUP:
 *   1) Cloudflare: create an R2 bucket (e.g. silkilinen-backups) + an API
 *      token with R2 read+write. Note the account id, access key, secret.
 *   2) Railway: in the same project click "+ New" → "Empty Service" (or
 *      duplicate this repo) → set Start Command:
 *          node backend/scripts/backupToR2.js
 *      then add a Cron schedule "0 3 * * *" (03:00 UTC). Copy MONGODB_URI
 *      from the API service and paste the five R2_* vars above.
 *   3) Trigger one run manually from Railway to confirm the file appears
 *      in R2. Then run the restore drill (restoreFromBackup.js).
 */

require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const zlib = require('zlib');
const { Readable } = require('stream');
const { MongoClient } = require('mongodb');
const {
  S3Client,
  PutObjectCommand,
  ListObjectsV2Command,
  DeleteObjectsCommand,
} = require('@aws-sdk/client-s3');

// Skip these system collections — they're regenerated by Mongo.
const SKIP = new Set(['system.indexes', 'system.namespaces', 'system.profile']);

function requireEnv(name) {
  if (!process.env[name]) throw new Error(`${name} is required`);
  return process.env[name];
}

function r2Client() {
  const accountId = requireEnv('R2_ACCOUNT_ID');
  return new S3Client({
    region: 'auto',
    endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
    credentials: {
      accessKeyId: requireEnv('R2_ACCESS_KEY_ID'),
      secretAccessKey: requireEnv('R2_SECRET_ACCESS_KEY'),
    },
  });
}

async function dumpAllCollections(mongoUri) {
  const client = new MongoClient(mongoUri);
  await client.connect();
  try {
    const db = client.db();
    const colls = (await db.listCollections().toArray())
      .map(c => c.name)
      .filter(n => !SKIP.has(n))
      .sort();

    const out = {
      meta: {
        createdAt: new Date().toISOString(),
        database: db.databaseName,
        collections: colls,
        version: 1,
      },
      collections: {},
    };

    let totalDocs = 0;
    for (const name of colls) {
      const docs = await db.collection(name).find({}).toArray();
      out.collections[name] = docs;
      totalDocs += docs.length;
      console.log(`  ${name.padEnd(28)} ${docs.length} docs`);
    }
    console.log(`Total: ${colls.length} collections, ${totalDocs} docs`);
    return out;
  } finally {
    await client.close();
  }
}

function gzipJson(obj) {
  // Use the standard JSON shape — ObjectId and Date both serialise via
  // their toJSON(). Restore reinflates them (see restoreFromBackup.js).
  return zlib.gzipSync(JSON.stringify(obj));
}

function backupKey(date = new Date()) {
  const iso = date.toISOString();
  const day = iso.slice(0, 10);
  const hms = iso.slice(11, 19).replace(/:/g, '-');
  return `silkilinen-${day}T${hms}Z.json.gz`;
}

async function uploadToR2(s3, bucket, key, buffer) {
  await s3.send(new PutObjectCommand({
    Bucket: bucket,
    Key: key,
    Body: Readable.from(buffer),
    ContentLength: buffer.length,
    ContentType: 'application/gzip',
  }));
}

// Delete archives older than `keepDays`. Matches our `silkilinen-*` prefix
// so it never touches anything else you might stash in the same bucket.
async function pruneOldBackups(s3, bucket, keepDays) {
  const cutoff = Date.now() - keepDays * 24 * 60 * 60 * 1000;
  const toDelete = [];
  let token;
  do {
    const page = await s3.send(new ListObjectsV2Command({
      Bucket: bucket,
      Prefix: 'silkilinen-',
      ContinuationToken: token,
    }));
    for (const obj of page.Contents || []) {
      const ts = obj.LastModified ? new Date(obj.LastModified).getTime() : 0;
      if (ts && ts < cutoff) toDelete.push({ Key: obj.Key });
    }
    token = page.IsTruncated ? page.NextContinuationToken : undefined;
  } while (token);

  if (!toDelete.length) {
    console.log('Prune: nothing older than retention.');
    return 0;
  }
  // DeleteObjects caps at 1000 keys per call.
  for (let i = 0; i < toDelete.length; i += 1000) {
    await s3.send(new DeleteObjectsCommand({
      Bucket: bucket,
      Delete: { Objects: toDelete.slice(i, i + 1000), Quiet: true },
    }));
  }
  console.log(`Prune: deleted ${toDelete.length} archive(s).`);
  return toDelete.length;
}

// Best-effort failure email. Silent success — you don't want 365/year.
async function sendFailureAlert(err) {
  const to = process.env.BACKUP_NOTIFY_EMAIL || process.env.ADMIN_EMAIL;
  if (!to || !process.env.RESEND_API_KEY) {
    console.log('No BACKUP_NOTIFY_EMAIL / RESEND_API_KEY — skipping alert.');
    return;
  }
  try {
    const { Resend } = require('resend');
    const resend = new Resend(process.env.RESEND_API_KEY);
    const from = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';
    await resend.emails.send({
      from,
      to,
      subject: '[SILKILINEN] Nightly backup FAILED',
      text: `The nightly Mongo backup failed at ${new Date().toISOString()}\n\nError: ${err.message}\n\nStack:\n${err.stack || '(none)'}`,
    });
    console.log(`Alert sent to ${to}`);
  } catch (mailErr) {
    console.error('Alert email failed too:', mailErr.message);
  }
}

async function main() {
  const t0 = Date.now();
  const mongoUri = requireEnv('MONGODB_URI');
  const bucket = requireEnv('R2_BUCKET');
  const keepDays = parseInt(process.env.BACKUP_RETENTION_DAYS || '30', 10);

  console.log(`[backup] Dumping MongoDB → R2 bucket "${bucket}"…`);
  const data = await dumpAllCollections(mongoUri);
  const archive = gzipJson(data);
  console.log(`[backup] Archive size: ${(archive.length / 1024 / 1024).toFixed(2)} MB`);

  const s3 = r2Client();
  const key = backupKey();
  await uploadToR2(s3, bucket, key, archive);
  console.log(`[backup] Uploaded: ${key}`);

  await pruneOldBackups(s3, bucket, keepDays);

  console.log(`[backup] Done in ${((Date.now() - t0) / 1000).toFixed(1)}s`);
}

main().catch(async err => {
  console.error('[backup] FAILED:', err.message);
  console.error(err.stack);
  await sendFailureAlert(err);
  process.exit(1);
});
