import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const server = fs.readFileSync(path.join(here, '..', 'server.js'), 'utf8');

// The API runs on api.silkilinen.com — a SUBDOMAIN of silkilinen.com, and
// therefore inside the Search Console DOMAIN property. That is why the domain
// property reports pages the https://www.silkilinen.com URL-prefix property
// cannot see: they are not on www.
//
// Nothing here ever told a crawler anything. The storefront's robots.txt is
// generated by Next and served on www; it has no authority over this host. And
// a JSON response has no <head>, so the meta tag the storefront uses for its
// private routes is not available — the directive has to be a header.
describe('the API host is not a website', () => {
  it('sends a noindex header', () => {
    expect(server).toMatch(/X-Robots-Tag/);
    expect(server).toMatch(/noindex/);
  });

  it('exempts /feed', () => {
    // The Pinterest product feed is INGESTED, not browsed. A channel whose job
    // is to pull the catalogue must never be handed a robots directive — the
    // failure is silent and the symptom is products quietly disappearing from
    // a channel nobody checks daily.
    expect(server).toMatch(/startsWith\('\/feed'\)/);
  });

  it('serves robots.txt, and does NOT disallow', () => {
    // Deliberate and easy to "tidy up" into a bug. A Disallow stops Google
    // FETCHING the URL, which means it never reads the noindex above — so
    // anything already in the index stays there, listed without a snippet.
    // Crawlable + noindex is the combination that removes them. Only once
    // Search Console shows the API URLs gone is a Disallow the right move.
    const route = server.slice(server.indexOf("app.get('/robots.txt'"));
    expect(route.slice(0, 300)).toMatch(/Allow: \//);
    expect(route.slice(0, 300)).not.toMatch(/Disallow: \//);
  });

  it('declares no sitemap — this host advertises nothing for crawling', () => {
    const route = server.slice(server.indexOf("app.get('/robots.txt'"));
    expect(route.slice(0, 300)).not.toMatch(/[Ss]itemap:/);
  });
});
